import rosalind

def translate(string):
	ret = ""
	AA = rosalind.SeqToAA(string[0:3])
	while len(string) >= 3:
		ret = ret + AA
		string = string[3:]
		if (len(string) < 3):
			return
		AA = rosalind.SeqToAA(string[0:3])
		if (AA == "STOP"):
			print(ret)
			return

def ORF_forward(string):
	for i in range(3):
		sub = string
		while (len(sub) > 3):
			AA = rosalind.SeqToAA(sub[0:3])
			if (AA == "M"):
				translate(sub)
			sub = sub[3:]
		string = string[1:]
	return (list)

def ORF_complete(string):
	ORF_forward(string)
	ORF_forward(rosalind.ComplementaryDNA(string)[::-1])

def RemoveDuplicate(sentences):
	sentences = set(sentences)
	for i in sentences:
		print(i)

ORF_complete("CCACATTGGCACACAACGTGGACCTTTCGAGGAGGTCACGGTGTCTATCAACCGTGAGGTGACACCGCCTCGGGCCGGGATCCGGGCCGACAAATTGATCCACGCCGTCAGAGCAGCGCCTATACTTATTGGTTCGATCATCGATGATTCGGACTTCCATCATCGTGCATCACTAGGGAGTTTATGCCAGGATCTCGTTTATATCCAAGAATATGTAAAATGAGTTACCTCTGTTGAGGAGCGCAGTCCTCGCAACACTTGCAGTTTGGCCCTTTTTAGTTGGATGCCCACTACAATGGGGTTTAGCTTAAGTTAACATCTTACCGTCTTCCGCACGAAGTCGATCAAAGACGCTGGGGACGGTTATTTACCTGAGGAAGGTGGCCCTTCGCTCGACGTGTCCTATGTGGATCAGGTACGTTTTAAACCTATAGCTATAGGTTTAAAACGTACCTGATCCACATGTCGGCTAAATTCATAAGAAATACAGAAATTTGGGCTTTCCAGAACATCTGTTCGGATTGCTCCTGGCTGATACAAAAATCGTTTCGAACTCCATGCGTATCCGATGGAATACCATACGTCTATTTACCTAGTGGCCATGAGACAAGTCTCCCGTGCGGTAGTGAAGTCGGCGGAGTAGCCACAATAGACTGGAAGATATTACCGCCTATATACGTTCGGCGCGGAGCTAGTTTCCCTCGTAGTACATTACTCCGCGGGGCACGTGATATTAGGATGTCTCGATATCCGCTTTCTTCCTGTCACGCACACTGTAGTTTTAGAGTGGAGTACGTTTTGCACTTAGTGTAAGTTTATAAAATCGCTGTCATGGGCTCTGAGATGTGTTCTATAATTATGTCGAGAC")
print("--------------------------")

sentences = rosalind.read_data("./temp.txt")
RemoveDuplicate(sentences)
